### ISSUE TITLE
第一个测试日志 | blinken的博客

### ISSUE THREAD

**Issue by LogicWen** [LogicWen/LogicWen.github.io#2]
https://logicwen.github.io/2018/09/12/%E6%B5%8B%E8%AF%95blog/ 

 这是附加一段文章摘要，字数最好在140字以内，会出现在meta的description里面

**Comment by LogicWen** [comment]
很强！
--说的就是你 <br />
*这是重点！*

**Comment by wenkangyu** [comment]
> @LogicWen
> 很强！
> --说的就是你 <br />
> *这是重点！*

什么意思

**Comment by LogicWen** [comment]
> @wenkangyu
> > @LogicWen
> > 很强！
> > --说的就是你 <br />
> > *这是重点！*
> 
> 什么意思

就是没意思的意思
